### ISSUE TITLE
integration in home assistant is not working

### ISSUE THREAD

**Issue by yossihaftzadi** [Guy293/Tami4EdgeAPI#10]
hi
Core
2024.7.0
Supervisor
2024.06.2
Operating System
12.4
Frontend
20240703.0
when i add the integration after i insert phone number i get otp to the phone
when i insert otp i get error "Unknown error occurred"

regards

**Comment by orenc75** [comment]
Same for me

**Comment by yossihaftzadi** [comment]
i found the problem
you need to change the ui language in the application from Hebrew to English

**Comment by orenc75** [comment]
Do you mean in the tami4 application? I tried it and it doesn't work...
But I have user profiles in Hebrew, maybe this is the problem?

**Comment by yossihaftzadi** [comment]
i only changed the tami4 application to English
check you are in the latest hassio version

**Comment by orenc75** [comment]
Yes, I am on the latest.
I changed the tami4 app to English but my tami4 machine is in hebrew, and some of the user profiles are writen in hebrew

**Comment by orenc75** [comment]
ok, I changed everyting to english, including the app, tami4 itself, profile names and cup names... Still not working for me.

**Comment by Guy293** [comment]
Hi, I'm currently debugging this issue, you can follow up here: https://github.com/home-assistant/core/issues/121675

**Comment by orenc75** [comment]
Great, thanks. It seems to match my error log as well.
