### ISSUE TITLE
README.md usage of submit_otp

### ISSUE THREAD

**Issue by danelkay93** [Guy293/Tami4EdgeAPI#3]
The readme code example contains the line `refresh_token = Tami4EdgeAPI.submit_otp(otp_code)` whereas it should be `refresh_token = Tami4EdgeAPI.submit_otp(phone_number, otp_code)`, according to that function's signature. I'd create a pull request myself, but I don't have write access.

**Comment by Guy293** [comment]
Hi! Thanks for contributing.
You can clone the repo, commit your changes, and create a pull request to this repo.

**Comment by danelkay93** [comment]
Awesome, thanks! I’ll take a look at the HomeAssistant stuff as well, when I get a chance.
