### ISSUE TITLE
Broken API

### ISSUE THREAD

**Issue by orenc75** [Guy293/Tami4EdgeAPI#8]
The API is broken for me for about a week.

This is what I get in response:
{'timestamp': 1718781239317,
 'status': 404,
 'error': 'Not Found',
 'message': 'No message available',
 'path': '/public/phone/generateOTP'}

Is it just me or did they change the API again?

**Comment by Guy293** [comment]
Hey did you update to the newest version?

**Comment by orenc75** [comment]
Hi,
Thank you. Updting to version 3.0 solved the problem.
However, the native HASS integration is still broken for me. Should I wait for HASS to get updated?

**Comment by Guy293** [comment]
Please see this thread: https://github.com/home-assistant/core/issues/113167#issuecomment-2178501391
