### ISSUE TITLE
 Tami4 Home Assistant Integration - still not working - SMS verification is still getting "Unexpected error"

### ISSUE THREAD

**Issue by NiiiYaa** [Guy293/Tami4EdgeAPI#9]
Hello,

It stopped working a few weeks ago.
When I tried to re-install is, the SMS is got "Unexpected error".
Every once in a while I'm trying again, but SMS verification is still getting "Unexpected error".
![2024-06-22 10_22_41-Settings – Home Assistant](https://github.com/Guy293/Tami4EdgeAPI/assets/113662601/a49c1f87-9224-48c1-830e-b4e1a1a59683)

**Comment by NiiiYaa** [comment]
Here is the log:

Logger: homeassistant.components.tami4.config_flow
Source: components/tami4/config_flow.py:46
integration: Tami4 Edge / Edge+ (documentation, issues)
First occurred: 10:14:46 AM (6 occurrences)
Last logged: 10:28:47 AM

Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/tami4/config_flow.py", line 46, in async_step_user
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/Tami4EdgeAPI/Tami4EdgeAPI.py", line 215, in request_otp
    if not response["success"]:
           ~~~~~~~~^^^^^^^^^^^
KeyError: 'success'

**Comment by Guy293** [comment]
Please refer to this thread: https://github.com/home-assistant/core/issues/113167#issuecomment-2178501391

**Comment by NiiiYaa** [comment]
Got it. Thank you!

**Comment by Crapy** [comment]
> Please refer to this thread: [home-assistant/core#113167 (comment)](https://github.com/home-assistant/core/issues/113167#issuecomment-2178501391)

Still not working even after the update
